---
title: "Übersicht"
subtitle: "Informationsvisualisierung"
author: "**Prof. Dr. André Calero Valdez**<br />" # can use md or html
date: ""
output:
  xaringan::moon_reader:
    seal: false
    css: ["default", "default-fonts", "imis.css"]  
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
library(stringr)
library(glue)
options(htmltools.dir.version = FALSE)
```

## Informationsvisualisierung
**Übersicht**
.pull-left[
```{r agenda, echo=FALSE, results='asis'}
# Write a function to read find all html files and get their titles and create a list
files <- dir(pattern = ".html")
files <- files[!files %in% c("index.html")]
rmds <- dir(pattern = ".Rmd")
res <- "\n<small>\n"
middle_index <- ceiling(length(files)/2)
for (i in 1:middle_index) {
  matching_rmd <- str_replace(files[i], ".html", ".Rmd")
  title <- rmarkdown::yaml_front_matter(matching_rmd)$title
  # generate List entries and links
  res <- paste0(res, 
                glue(" {i-1} - {title} [Link]({files[i]})<br/>\n")
                )
}
res <- paste0(res, "</small>")
cat(res)

# TODO: move figures to includegraphics
# TODO: separate topics in individual smaller chunks
```
]

.pull-right[
```{r agenda2, echo=FALSE, results='asis'}

res <- "\n<small>\n"
for (i in (middle_index+1):length(files)) {
  matching_rmd <- str_replace(files[i], ".html", ".Rmd")
  title <- rmarkdown::yaml_front_matter(matching_rmd)$title
  # generate List entries and links
  res <- paste0(res, 
                glue(" {i-1} - {title} [Link]({files[i]})<br/>\n")
                )
}
res <- paste0(res, "</small>")
cat(res)

# TODO: move figures to includegraphics
# TODO: separate topics in individual smaller chunks
```
]
